
import os
from typing import Optional, List, Union
from pydantic import BaseSettings, Field

class SystemSettings(BaseSettings):
    """
    Centralized system-level configuration.
    Reads from .env at startup. Immutable at runtime.
    """
    
    # Infrastructure
    DATABASE_URL: str = Field(..., env="DATABASE_URL")
    REDIS_URL: str = Field("redis://localhost:6379/0", env="REDIS_URL")
    CELERY_BROKER_URL: str = Field("redis://localhost:6379/0", env="CELERY_BROKER_URL")
    CELERY_RESULT_BACKEND: str = Field("redis://localhost:6379/1", env="CELERY_RESULT_BACKEND")
    
    # LLM Infrastructure
    LLM_PROVIDER: str = Field("openai", env="LLM_PROVIDER")
    LLM_MODEL: str = Field("gpt-4o", env="LLM_MODEL")
    LLM_TEMPERATURE: float = Field(0.0, env="LLM_TEMPERATURE")
    LLM_MAX_TOKENS: int = Field(1000, env="LLM_MAX_TOKENS")
    NVIDIA_BASE_URL: Optional[str] = Field(None, env="NVIDIA_BASE_URL")
    NVIDIA_API_KEY: Optional[str] = Field(None, env="NVIDIA_API_KEY")
    OPENAI_API_KEY: Optional[str] = Field(None, env="OPENAI_API_KEY")
    
    # Hard System Safety Caps
    FETCH_RESULTS_LIMIT: int = Field(10, env="FETCH_RESULTS_LIMIT")
    FETCH_BATCH_SIZE: int = Field(1, env="FETCH_BATCH_SIZE")
    FETCH_PROVIDERS: str = Field("semantic_scholar", env="FETCH_PROVIDERS")
    FETCH_TIMEOUT_SECONDS: int = Field(30, env="FETCH_TIMEOUT_SECONDS")
    FETCH_RETRY_ATTEMPTS: int = Field(3, env="FETCH_RETRY_ATTEMPTS")
    
    FETCH_TOP_K_HYPOTHESES: int = Field(1, env="FETCH_TOP_K_HYPOTHESES")
    FETCH_MIN_REPUTATION: int = Field(-10, env="FETCH_MIN_REPUTATION")
    
    # New Safety Caps
    SYSTEM_MAX_PAPERS_PER_JOB: int = Field(100, env="SYSTEM_MAX_PAPERS_PER_JOB")
    SYSTEM_MAX_FETCH_CYCLES: int = Field(5, env="SYSTEM_MAX_FETCH_CYCLES")
    SYSTEM_MAX_GRAPH_SIZE: int = Field(5000, env="SYSTEM_MAX_GRAPH_SIZE")
    
    # Algorithm Invariants
    SEMANTIC_SIMILARITY_THRESHOLD: float = Field(0.85, env="SEMANTIC_SIMILARITY_THRESHOLD")
    PATH_REASONING_MAX_HOPS: int = Field(2, env="PATH_REASONING_MAX_HOPS")
    PATH_REASONING_ALLOW_LEN3: bool = Field(False, env="PATH_REASONING_ALLOW_LEN3")
    PATH_REASONING_SEEDS: str = Field("", env="PATH_REASONING_SEEDS")
    PATH_REASONING_STOPLIST: str = Field("", env="PATH_REASONING_STOPLIST")
    
    FINGERPRINT_ALGORITHM: str = Field("minhash", env="FINGERPRINT_ALGORITHM")
    FINGERPRINT_SIMILARITY_THRESHOLD: float = Field(0.9, env="FINGERPRINT_SIMILARITY_THRESHOLD")
    FINGERPRINT_COMPONENTS: str = Field("content", env="FINGERPRINT_COMPONENTS")
    
    # Ingestion Configuration
    INGESTION_SEGMENTATION_STRATEGY: str = Field("sentences", env="INGESTION_SEGMENTATION_STRATEGY")
    INGESTION_SENTENCES_PER_BLOCK: int = Field(3, env="INGESTION_SENTENCES_PER_BLOCK")
    ENABLE_LEXICAL_REPAIR: bool = Field(False, env="ENABLE_LEXICAL_REPAIR")
    
    INDIRECT_PATH_MEASUREMENTS_ENABLED: bool = Field(True, env="INDIRECT_PATH_MEASUREMENTS_ENABLED")
    INDIRECT_PATH_TEMPORAL_PLACEHOLDERS: bool = Field(False, env="INDIRECT_PATH_TEMPORAL_PLACEHOLDERS")
    
    # Domain Resolution
    DOMAIN_DETERMINISTIC_THRESHOLD: float = Field(0.7, env="DOMAIN_DETERMINISTIC_THRESHOLD")
    DOMAIN_LLM_THRESHOLD: float = Field(0.6, env="DOMAIN_LLM_THRESHOLD")
    DOMAIN_LABELS: str = Field("biomedical,computer_science,physics,chemistry,mathematics,engineering", env="DOMAIN_LABELS")
    DOMAIN_KEYWORDS: str = Field("{}", env="DOMAIN_KEYWORDS")
    DOMAIN_RESOLVER_PROMPT_FILE: str = Field("domain_resolver.txt", env="DOMAIN_RESOLVER_PROMPT_FILE")
    
    # Query Orchestration
    QUERY_SIGNATURE_LENGTH: int = Field(64, env="QUERY_SIGNATURE_LENGTH")
    QUERY_INITIAL_REPUTATION: int = Field(0, env="QUERY_INITIAL_REPUTATION")
    QUERY_REPUTATION_EXHAUSTION_DECAY: int = Field(-5, env="QUERY_REPUTATION_EXHAUSTION_DECAY")
    QUERY_MAX_REUSE_ATTEMPTS: int = Field(3, env="QUERY_MAX_REUSE_ATTEMPTS")
    
    # Decision Logic
    DECISION_CONFIDENCE_NORM_FACTOR: int = Field(10, env="DECISION_CONFIDENCE_NORM_FACTOR")
    DECISION_HIGH_CONFIDENCE_THRESHOLD: float = Field(0.7, env="DECISION_HIGH_CONFIDENCE_THRESHOLD")
    DECISION_DOMINANT_GAP_RATIO: float = Field(0.3, env="DECISION_DOMINANT_GAP_RATIO")
    DECISION_LOW_DIVERSITY_PAIRS_THRESHOLD: int = Field(2, env="DECISION_LOW_DIVERSITY_PAIRS_THRESHOLD")
    DECISION_DIVERSITY_RATIO_THRESHOLD: float = Field(0.3, env="DECISION_DIVERSITY_RATIO_THRESHOLD")
    DECISION_SPARSE_GRAPH_DENSITY_THRESHOLD: float = Field(0.05, env="DECISION_SPARSE_GRAPH_DENSITY_THRESHOLD")
    DECISION_PATH_SUPPORT_THRESHOLD: int = Field(2, env="DECISION_PATH_SUPPORT_THRESHOLD")
    DECISION_STABILITY_CYCLE_THRESHOLD: int = Field(3, env="DECISION_STABILITY_CYCLE_THRESHOLD")
    DECISION_PASSED_TO_TOTAL_RATIO_THRESHOLD: float = Field(0.2, env="DECISION_PASSED_TO_TOTAL_RATIO_THRESHOLD")
    DECISION_MINIMUM_HYPOTHESES_THRESHOLD: int = Field(1, env="DECISION_MINIMUM_HYPOTHESES_THRESHOLD")
    
    # Handlers
    CLARIFICATION_USE_LLM: int = Field(0, env="CLARIFICATION_USE_LLM")
    
    # Indirect Path Measurements
    INDIRECT_PATH_DOMINANCE_GAP_THRESHOLD: float = Field(0.2, env="INDIRECT_PATH_DOMINANCE_GAP_THRESHOLD")
    INDIRECT_PATH_MIN_LENGTH: int = Field(3, env="INDIRECT_PATH_MIN_LENGTH")
    INDIRECT_PATH_MAX_LENGTH: int = Field(4, env="INDIRECT_PATH_MAX_LENGTH")
    
    # Signal Computation
    SIGNAL_POSITIVE_THRESHOLD: float = Field(1.0, env="SIGNAL_POSITIVE_THRESHOLD")
    SIGNAL_NEGATIVE_THRESHOLD: float = Field(-1.0, env="SIGNAL_NEGATIVE_THRESHOLD")
    SIGNAL_REPUTATION_POSITIVE_DELTA: int = Field(10, env="SIGNAL_REPUTATION_POSITIVE_DELTA")
    SIGNAL_REPUTATION_NEGATIVE_DELTA: int = Field(-20, env="SIGNAL_REPUTATION_NEGATIVE_DELTA")
    
    SIGNAL_WEIGHT_PASSED_HYPOTHESIS_COUNT: float = Field(1.0, env="SIGNAL_WEIGHT_PASSED_HYPOTHESIS_COUNT")
    SIGNAL_WEIGHT_MEAN_CONFIDENCE: float = Field(0.8, env="SIGNAL_WEIGHT_MEAN_CONFIDENCE")
    SIGNAL_WEIGHT_GRAPH_DENSITY: float = Field(0.5, env="SIGNAL_WEIGHT_GRAPH_DENSITY")
    SIGNAL_WEIGHT_FILTERED_RATIO: float = Field(0.3, env="SIGNAL_WEIGHT_FILTERED_RATIO")
    
    SIGNAL_MAX_DELTA_PASSED_HYPOTHESIS_COUNT: float = Field(100.0, env="SIGNAL_MAX_DELTA_PASSED_HYPOTHESIS_COUNT")
    SIGNAL_MAX_DELTA_MEAN_CONFIDENCE: float = Field(20.0, env="SIGNAL_MAX_DELTA_MEAN_CONFIDENCE")
    SIGNAL_MAX_DELTA_GRAPH_DENSITY: float = Field(0.2, env="SIGNAL_MAX_DELTA_GRAPH_DENSITY")
    SIGNAL_MAX_DELTA_FILTERED_RATIO: float = Field(0.5, env="SIGNAL_MAX_DELTA_FILTERED_RATIO")

    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"
        case_sensitive = True

# Singleton instance
system_settings = SystemSettings()
