"""initial refactored schema

Revision ID: 067894ffcddf
Revises: 
Create Date: 2026-01-04 11:26:35.373850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '067894ffcddf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=True)
    op.create_table('decision_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('decision_label', sa.String(), nullable=False),
    sa.Column('provider_used', sa.String(), nullable=False),
    sa.Column('measurements_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('fallback_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_results_job_id'), 'decision_results', ['job_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('origin_type', sa.String(), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_job_id'), 'files', ['job_id'], unique=False)
    op.create_index(op.f('ix_files_paper_id'), 'files', ['paper_id'], unique=False)
    op.create_table('ingestion_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_sources_job_id'), 'ingestion_sources', ['job_id'], unique=False)
    op.create_index(op.f('ix_ingestion_sources_processed'), 'ingestion_sources', ['processed'], unique=False)
    op.create_table('reasoning_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reasoning_queries_job_id'), 'reasoning_queries', ['job_id'], unique=False)
    op.create_table('semantic_graphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('graph', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_graphs_job_id'), 'semantic_graphs', ['job_id'], unique=True)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('related_decision_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['related_decision_id'], ['decision_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_created_at'), 'conversation_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_messages_job_id'), 'conversation_messages', ['job_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_related_decision_id'), 'conversation_messages', ['related_decision_id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('predicates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.Column('passed_filter', sa.Boolean(), nullable=False),
    sa.Column('filter_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['reasoning_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_job_id'), 'hypotheses', ['job_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_query_id'), 'hypotheses', ['query_id'], unique=False)
    op.create_table('text_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('ingestion_source_id', sa.Integer(), nullable=False),
    sa.Column('block_text', sa.Text(), nullable=False),
    sa.Column('block_order', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(), nullable=False),
    sa.Column('segmentation_strategy', sa.String(), nullable=False),
    sa.Column('triples_extracted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_source_id'], ['ingestion_sources.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_blocks_ingestion_source_id'), 'text_blocks', ['ingestion_source_id'], unique=False)
    op.create_index(op.f('ix_text_blocks_job_id'), 'text_blocks', ['job_id'], unique=False)
    op.create_table('triples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('ingestion_source_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('predicate', sa.String(), nullable=False),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('extractor_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['text_blocks.id'], ),
    sa.ForeignKeyConstraint(['ingestion_source_id'], ['ingestion_sources.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triples_block_id'), 'triples', ['block_id'], unique=False)
    op.create_index(op.f('ix_triples_ingestion_source_id'), 'triples', ['ingestion_source_id'], unique=False)
    op.create_index(op.f('ix_triples_job_id'), 'triples', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triples_job_id'), table_name='triples')
    op.drop_index(op.f('ix_triples_ingestion_source_id'), table_name='triples')
    op.drop_index(op.f('ix_triples_block_id'), table_name='triples')
    op.drop_table('triples')
    op.drop_index(op.f('ix_text_blocks_job_id'), table_name='text_blocks')
    op.drop_index(op.f('ix_text_blocks_ingestion_source_id'), table_name='text_blocks')
    op.drop_table('text_blocks')
    op.drop_index(op.f('ix_hypotheses_query_id'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_job_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_conversation_messages_related_decision_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_job_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_created_at'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_semantic_graphs_job_id'), table_name='semantic_graphs')
    op.drop_table('semantic_graphs')
    op.drop_index(op.f('ix_reasoning_queries_job_id'), table_name='reasoning_queries')
    op.drop_table('reasoning_queries')
    op.drop_index(op.f('ix_ingestion_sources_processed'), table_name='ingestion_sources')
    op.drop_index(op.f('ix_ingestion_sources_job_id'), table_name='ingestion_sources')
    op.drop_table('ingestion_sources')
    op.drop_index(op.f('ix_files_paper_id'), table_name='files')
    op.drop_index(op.f('ix_files_job_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_decision_results_job_id'), table_name='decision_results')
    op.drop_table('decision_results')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_table('papers')
    op.drop_table('jobs')
    # ### end Alembic commands ###
