"""refactor_paper_tracking

Revision ID: 23785768504c
Revises: 068_fetch_more
Create Date: 2026-01-18 20:43:31.921092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23785768504c'
down_revision: Union[str, Sequence[str], None] = '068_fetch_more'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'used_for_research')
    op.alter_column('search_query_runs', 'candidates_fetched',
               existing_type=sa.INTEGER(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using="'[]'::jsonb")
    op.alter_column('search_query_runs', 'candidates_accepted',
               existing_type=sa.INTEGER(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using="'[]'::jsonb")
    op.alter_column('search_query_runs', 'candidates_rejected',
               existing_type=sa.INTEGER(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using="'[]'::jsonb")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_query_runs', 'candidates_rejected',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('search_query_runs', 'candidates_accepted',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('search_query_runs', 'candidates_fetched',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('papers', sa.Column('used_for_research', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
