"""alter hypothesis table for filter related columns

Revision ID: d2284c118fb0
Revises: c3d5e6f7g8h9
Create Date: 2025-12-30 21:46:56.442526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2284c118fb0'
down_revision: Union[str, Sequence[str], None] = 'c3d5e6f7g8h9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hypotheses', sa.Column('passed_filter', sa.Boolean(), nullable=False))
    op.add_column('hypotheses', sa.Column('filter_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_semantic_graphs_job_id'), table_name='semantic_graphs')
    op.alter_column('text_blocks', 'triples_extracted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('text_blocks', 'triples_extracted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_semantic_graphs_job_id'), 'semantic_graphs', ['job_id'], unique=False)
    op.drop_column('hypotheses', 'filter_reason')
    op.drop_column('hypotheses', 'passed_filter')
    # ### end Alembic commands ###
