"""add triples table and triples_extracted flag

Revision ID: db9c870c0f1d
Revises: 22df52f21aac
Create Date: 2025-12-25 00:08:01.498971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9c870c0f1d'
down_revision: Union[str, Sequence[str], None] = '22df52f21aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('predicate', sa.String(), nullable=False),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('extractor_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['text_blocks.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ingestion_sources', sa.Column('extracted_urls', sa.JSON(), nullable=True))
    op.add_column('text_blocks',sa.Column('triples_extracted',sa.Boolean(),nullable=False,server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_blocks', 'triples_extracted')
    op.drop_column('ingestion_sources', 'extracted_urls')
    op.drop_table('triples')
    # ### end Alembic commands ###
