"""verification and search

Revision ID: 1b1da273bd86
Revises: 8870d504df00
Create Date: 2026-02-27 12:09:43.904682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b1da273bd86'
down_revision: Union[str, Sequence[str], None] = '8870d504df00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('connection_found', sa.Boolean(), nullable=True),
    sa.Column('connection_type', sa.String(), nullable=True),
    sa.Column('path', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('supporting_papers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_results_job_id'), 'verification_results', ['job_id'], unique=False)
    op.add_column('jobs', sa.Column('mode', sa.String(), server_default='discovery', nullable=False))
    op.add_column('jobs', sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('search_queries', sa.Column('entities_used', sa.JSON(), nullable=True))
    op.add_column('search_queries', sa.Column('entities_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_search_queries_entities_hash'), 'search_queries', ['entities_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_queries_entities_hash'), table_name='search_queries')
    op.drop_column('search_queries', 'entities_hash')
    op.drop_column('search_queries', 'entities_used')
    op.drop_column('jobs', 'result')
    op.drop_column('jobs', 'mode')
    op.drop_index(op.f('ix_verification_results_job_id'), table_name='verification_results')
    op.drop_table('verification_results')
    # ### end Alembic commands ###
