"""sources added to the hypo table

Revision ID: 2e5bdb94b8ad
Revises: 8cbd3f0bf277
Create Date: 2026-02-14 06:41:26.768161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e5bdb94b8ad'
down_revision: Union[str, Sequence[str], None] = '8cbd3f0bf277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hypotheses', sa.Column('source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('hypotheses', sa.Column('triple_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('hypotheses', sa.Column('block_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hypotheses', 'block_ids')
    op.drop_column('hypotheses', 'triple_ids')
    op.drop_column('hypotheses', 'source_ids')
    # ### end Alembic commands ###
