"""splited seachquery run by Job Specific table and searchquery run

Revision ID: 2effca134c3d
Revises: 2e5bdb94b8ad
Create Date: 2026-02-15 06:38:53.750521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2effca134c3d'
down_revision: Union[str, Sequence[str], None] = '2e5bdb94b8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_paper_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('evaluated', sa.Boolean(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('hypo_ref_count', sa.Integer(), nullable=False),
    sa.Column('cumulative_conf', sa.Float(), nullable=False),
    sa.Column('entity_density', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['search_query_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_paper_evidence_job_id'), 'job_paper_evidence', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_paper_evidence_paper_id'), 'job_paper_evidence', ['paper_id'], unique=False)
    op.create_index(op.f('ix_job_paper_evidence_run_id'), 'job_paper_evidence', ['run_id'], unique=False)
    op.drop_column('search_query_runs', 'fetched_paper_ids')
    op.drop_column('search_query_runs', 'rejected_paper_ids')
    op.drop_column('search_query_runs', 'accepted_paper_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_query_runs', sa.Column('accepted_paper_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('search_query_runs', sa.Column('rejected_paper_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('search_query_runs', sa.Column('fetched_paper_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_job_paper_evidence_run_id'), table_name='job_paper_evidence')
    op.drop_index(op.f('ix_job_paper_evidence_paper_id'), table_name='job_paper_evidence')
    op.drop_index(op.f('ix_job_paper_evidence_job_id'), table_name='job_paper_evidence')
    op.drop_table('job_paper_evidence')
    # ### end Alembic commands ###
