"""add graph versioning

Revision ID: 8870d504df00
Revises: 2effca134c3d
Create Date: 2026-02-20 13:38:01.599863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8870d504df00'
down_revision: Union[str, Sequence[str], None] = '2effca134c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hypotheses', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('hypotheses', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('hypotheses', sa.Column('affected_by_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('semantic_graphs', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('semantic_graphs', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_semantic_graphs_job_id'), table_name='semantic_graphs')
    op.create_index(op.f('ix_semantic_graphs_job_id'), 'semantic_graphs', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_graphs_job_id'), table_name='semantic_graphs')
    op.create_index(op.f('ix_semantic_graphs_job_id'), 'semantic_graphs', ['job_id'], unique=True)
    op.drop_column('semantic_graphs', 'is_active')
    op.drop_column('semantic_graphs', 'version')
    op.drop_column('hypotheses', 'affected_by_nodes')
    op.drop_column('hypotheses', 'is_active')
    op.drop_column('hypotheses', 'version')
    # ### end Alembic commands ###
