"""add domain to hypothesis

Revision ID: 8cbd3f0bf277
Revises: d0d51641fbe0
Create Date: 2026-02-10 16:13:25.012618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cbd3f0bf277'
down_revision: Union[str, Sequence[str], None] = 'd0d51641fbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hypotheses', sa.Column('domain', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hypotheses', 'domain')
    # ### end Alembic commands ###
